
# This is the user-interface definition of a Shiny web application.
# You can find out more about building applications with Shiny here:
#
# http://shiny.rstudio.com
#

library(shiny)

shinyUI(fluidPage(
  
  # Application title
  titlePanel("Locate! — Den eigenen Alltag im Wintersemester 2015/2016 vergleichen."),
  
  mainPanel(
    tabsetPanel(
      tabPanel("Dateneingabe",
               fluidRow(
                 column(4,
                        h4("Persönliche Situation"),
                        textInput("name", "Name:", "Jean-Paul"),
                        radioButtons("wohnort", "Wohnort während dem Semester:",
                                     c("Wohnort: eigene Wohnung",
                                       "Wohnort: Eltern",
                                       "Wohnort: Partner/in",
                                       "Wohnort: WG/ Wohnheim")),
                        radioButtons("entfernung_ph", "Entfernung des Wohnorts zur PH:",
                                     c("0 bis 10km", 
                                       "11 bis 25km", 
                                       "26 bis 150km")),
                        radioButtons("finanzierung_eltern", "Finanzierung durch die Eltern:",
                                     c("hauptsächlich" = "finanzierung_eltern_hauptsächlich",
                                       "teilweise" = "finanzierung_eltern_teilweise",
                                       "nein" = "finanzierung_eltern_nein")),
                        radioButtons("finanzierung_arbeit_vorlesungszeit", "Finanzierung durch Arbeit während dem Semester:",
                                     c("hauptsächlich" = "finanzierung_arbeit_vorlesungszeit_hauptsächlich",
                                       "teilweise" = "finanzierung_arbeit_vorlesungszeit_teilweise",
                                       "nein" = "finanzierung_arbeit_vorlesungszeit_nein")),
                        radioButtons("finanzierung_arbeit_semesterferien", "Finanzierung durch Arbeit während den Semesterferien:",
                                     c("hauptsächlich" = "finanzierung_arbeit_semesterferien_hauptsächlich",
                                       "teiweise" = "finanzierung_arbeit_semesterferien_teilweise",
                                       "nein" = "finanzierung_arbeit_semesterferien_nein"))
                 ),
                 column(4,
                        h4("Gewöhnliche Studienwoche"),
                        radioButtons("zeitmuster", "Geschätztes Zeitmuster:",
                                     c("Zeitmuster 1: Freizeit",
                                       "Zeitmuster 2: Selbststudium",
                                       "Zeitmuster 3: Erwerbsarbeit",
                                       "Zeitmuster 4: Pendler/innen")),
                        radioButtons("lehrveranstaltungen_anzahl", "Anzahl der besuchten Lehrveranstaltungen:",
                                     c("11 bis 12 Veranstaltungen", 
                                       "13 Veranstaltungen",    
                                       "bis 10 Veranstaltungen",
                                       "mehr als 13 Veranstaltungen")),
                        radioButtons("lernort_alleine", "Lieblingslernort alleine:",
                                     c("Lernort: PH",
                                       "Lernort: PH und Zuhause",
                                       "Lernort: Zuhause")),
                        radioButtons("selbstorganisierte_lerngruppe", "Teilnahme an einer Lerngruppe:",
                                     c("Lerngruppe: ja",
                                       "Lerngruppe: gelegentlich",
                                       "Lerngruppe: nein")),
                        radioButtons("aufmerksamkeit", "Zeit mit der größten Aufmerksamkeit:",
                                     c("Aufmerksamkeit: morgens",
                                       "Aufmerksamkeit: mittags",            
                                       "Aufmerksamkeit: nachmittags",
                                       "Aufmerksamkeit: abends")),
                        radioButtons("sitzplatz", "Lieblingsposition in einem Seminarzimmer:",
                                     c("Sitzplatz: vorderes Drittel",
                                       "Sitzplatz: Mitte",
                                       "Sitzplatz: hinteres Drittel")),
                        radioButtons("sitzplatz_identisch", "Identischer Sitzplatz",
                                     c("Sitzplatz identisch: selten",
                                       "Sitzplatz identisch: ab und zu",
                                       "Sitzplatz identisch: oft",
                                       "Sitzplatz identisch: immer"))
                 ),
                 column(4,
                        h4("Studienalltag an der PH"),
                        radioButtons("ph_hsb_recherchieren", "In der HSB recherchieren:",
                                     c("nie" = "ph_hsb_recherchieren_nie",
                                       "selten" = "ph_hsb_recherchieren_selten",
                                       "manchmal" = "ph_hsb_recherchieren_manchmal",
                                       "oft" = "ph_hsb_recherchieren_oft")),
                        radioButtons("ph_hsb_lernen", "In der HSB lernen:",
                                     c("nie" = "ph_hsb_lernen_nie",
                                       "selten" = "ph_hsb_lernen_selten",
                                       "manchmal" = "ph_hsb_lernen_manchmal",
                                       "oft" = "ph_hsb_lernen_oft")),
                        radioButtons("mensa_essen", "In der Mensa essen:",
                                     c("nie" = "mensa_essen_nie",
                                       "selten" = "mensa_essen_selten",
                                       "manchmal" = "mensa_essen_manchmal",
                                       "oft" = "mensa_essen_oft")),
                        radioButtons("cafete_essen", "In der Cafete essen:",
                                     c("nie" = "cafete_essen_nie",
                                       "oft" = "cafete_essen_oft",
                                       "selten" = "cafete_essen_selten",
                                       "manchmal" = "cafete_essen_manchmal")),
                        radioButtons("computerräume_nutzen", "Computerräume nutzen:",
                                     c("nie" = "computerräume_nutzen_nie",
                                       "selten" = "computerräume_nutzen_selten",
                                       "manchmal" = "computerräume_nutzen_manchmal",
                                       "oft" = "computerräume_nutzen_oft")),
                        radioButtons("campus_lernen", "Am Campus lernen:",
                                     c("nie" = "campus_lernen_nie",
                                       "selten" = "campus_lernen_selten",
                                       "manchmal" = "campus_lernen_manchmal",
                                       "oft" = "campus_lernen_oft")),
                        radioButtons("campus_entspannen", "Am Campus entspannen:",
                                     c("nie" = "campus_entspannen_nie",
                                       "selten" = "campus_entspannen_selten",
                                       "manchmal" = "campus_entspannen_manchmal",
                                       "oft" = "campus_entspannen_oft")),
                        radioButtons("austausch_lehrende", "Mit Lehrenden austauschen:",
                                     c("nie" = "austausch_lehrende_nie",
                                       "selten" = "austausch_lehrende_selten",
                                       "manchmal" = "austausch_lehrende_manchmal",
                                       "oft" = "austausch_lehrende_oft")),
                        radioButtons("ph_kommilitoninnen_entspannen", "Mit Kommiliton/innen entspannen:",
                                     c("nie" = "ph_kommilitoninnen_entspannen_nie",
                                       "selten" = "ph_kommilitoninnen_entspannen_selten",
                                       "manchmal" = "ph_kommilitoninnen_entspannen_manchmal",
                                       "oft" = "ph_kommilitoninnen_entspannen_oft")),
                        radioButtons("ph_kommilitoninnen_lernen", "Mit Kommiliton/innen lernen:",
                                     c("nie" = "ph_kommilitoninnen_lernen_nie",
                                       "selten" = "ph_kommilitoninnen_lernen_selten",
                                       "manchmal" = "ph_kommilitoninnen_lernen_manchmal",
                                       "oft" = "ph_kommilitoninnen_lernen_oft"))
                 ),
                 column(4,
                        h4("Studienalltag außerhalb der PH"),
                        radioButtons("ka_essen", "In Karlsruhe essen:",
                                     c("nie" = "ka_essen_nie",
                                       "selten" = "ka_essen_selten",
                                       "manchmal" = "ka_essen_manchmal",
                                       "oft" = "ka_essen_oft")),
                        radioButtons("ka_entspannen", "In Karlsruhe entspannen:",
                                     c("nie" = "ka_entspannen_nie",
                                       "selten" = "ka_entspannen_selten",
                                       "manchmal" = "ka_entspannen_manchmal",
                                       "oft" = "ka_entspannen_oft")),
                        radioButtons("bahn_lernen", "In der Bahn lernen:",
                                     c("nie" = "bahn_lernen_nie",
                                       "selten" = "bahn_lernen_selten",
                                       "manchmal" = "bahn_lernen_manchmal",
                                       "oft" = "bahn_lernen_oft")),
                        radioButtons("fremder_wohnort_lernen", "An einem fremden Wohnort lernen:",
                                     c("nie" = "fremder_wohnort_lernen_nie",
                                       "selten" = "fremder_wohnort_lernen_selten",
                                       "manchmal" = "fremder_wohnort_lernen_manchmal",
                                       "oft" = "fremder_wohnort_lernen_oft")),
                        radioButtons("kommilitoninnen_treffen", "Mit Kommiliton/innen treffen:",
                                     c("nie" = "kommilitoninnen_treffen_nie",
                                       "selten" = "kommilitoninnen_treffen_selten",
                                       "manchmal" = "kommilitoninnen_treffen_manchmal",
                                       "oft" = "kommilitoninnen_treffen_oft")),
                        radioButtons("kommilitoninnen_lernen", "Mit Kommiliton/innen lernen:",
                                     c("nie" = "kommilitoninnen_lernen_nie",
                                       "selten" = "kommilitoninnen_lernen_selten",
                                       "manchmal" = "kommilitoninnen_lernen_manchmal",
                                       "oft" = "kommilitoninnen_lernen_oft"))
                 ),
                 column(4,
                        h4("Gewöhnliche Internetnutzung für das Studium"),
                        radioButtons("website_nutzen", "PH Website nutzen:",
                                     c("selten" = "website_nutzen_selten",
                                       "manchmal" = "website_nutzen_manchmal",
                                       "oft" = "website_nutzen_oft")),
                        radioButtons("web_services_andere_nutzen", "Andere Web Services nutzen:",
                                     c("nie" = "web_services_andere_nutzen_nie",
                                       "selten" = "web_services_andere_nutzen_selten",
                                       "manchmal" = "web_services_andere_nutzen_manchmal",
                                       "oft" = "web_services_andere_nutzen_oft")),
                        radioButtons("emails_lehrende", "E-Mails an Lehrende schreiben:",
                                     c("nie" = "emails_lehrende_nie",
                                       "selten" = "emails_lehrende_selten",
                                       "manchmal" = "emails_lehrende_manchmal",
                                       "oft" = "emails_lehrende_oft")),
                        radioButtons("emails_kommilitoninnen", "E-Mails an Kommiliton/innen schreiben:",
                                     c("nie" = "emails_kommilitoninnen_nie",
                                       "selten" = "emails_kommilitoninnen_selten",
                                       "manchmal" = "emails_kommilitoninnen_manchmal",
                                       "oft" = "emails_kommilitoninnen_oft")),
                        radioButtons("internetrecherche", "Im Internet recherchieren:",
                                     c("manchmal" = "internetrecherche_manchmal",
                                       "selten" = "internetrecherche_selten",
                                       "oft" = "internetrecherche_oft")),
                        radioButtons("soziale_netzwerke_studieren", "Soziale Netzwerke fürs Studium nutzen:",
                                     c("nie" = "soziale_netzwerke_studieren_nie",
                                       "selten" = "soziale_netzwerke_studieren_selten",
                                       "manchmal" = "soziale_netzwerke_studieren_manchmal",
                                       "oft" = "soziale_netzwerke_studieren_oft"))
                 ),
                 column(4,
                        h4("Alltägliche Freizeitaktivitäten"),
                        radioButtons("fernsehen", "Fernsehen:", 
                                     c("selten" = "fernsehen_selten",
                                       "manchmal" = "fernsehen_manchmal",
                                       "oft" = "fernsehen_oft")),
                        radioButtons("musik", "Musik:",
                                     c("selten" = "musik_selten",
                                       "manchmal" = "musik_manchmal",
                                       "oft" = "musik_oft")),
                        radioButtons("kino", "Kino:",
                                     c("selten" = "kino_selten",
                                       "manchmal" = "kino_manchmal",
                                       "oft" = "kino_oft")),
                        radioButtons("freunde_treffen", "Freunde treffen:",
                                     c("selten" = "freunde_treffen_selten",
                                       "manchmal" = "freunde_treffen_manchmal",
                                       "oft" = "freunde_treffen_oft")),
                        radioButtons("soziale_netzwerke", "Soziale Netzwerke nutzen:",
                                     c("selten" = "soziale_netzwerke_selten",
                                       "manchmal" = "soziale_netzwerke_manchmal",
                                       "oft" = "soziale_netzwerke_oft")),
                        radioButtons("internet_surfen", "Im Internet surfen:",
                                     c("selten" = "internet_surfen_selten",
                                       "manchmal" = "internet_surfen_manchmal",
                                       "oft" = "internet_surfen_oft")),
                        radioButtons("chillen", "Chillen:",
                                     c("selten" = "chillen_selten",
                                       "manchmal" = "chillen_manchmal",
                                       "oft" = "chillen_oft")),
                        radioButtons("zeitungen", "Zeitungen lesen:",
                                     c("selten" = "zeitungen_selten",
                                       "manchmal" = "zeitungen_manchmal",
                                       "oft" = "zeitungen_oft")),
                        radioButtons("disco", "In die Disco gehen:",
                                     c("selten" = "disco_selten",
                                       "manchmal" = "disco_manchmal",
                                       "oft" = "disco_oft")),
                        radioButtons("sport", "Sport:",
                                     c("selten" = "sport_selten",
                                       "manchmal" = "sport_manchmal",
                                       "oft" = "sport_oft")),
                        radioButtons("familie", "Etwas mit der Familie unternehmen:",
                                     c("selten" = "familie_selten",
                                       "manchmal" = "familie_manchmal",
                                       "oft" = "familie_oft")),
                        radioButtons("shoppen", "Shoppen:",
                                     c("selten" = "shoppen_selten",
                                       "manchmal" = "shoppen_manchmal",
                                       "oft" = "shoppen_oft")),
                        radioButtons("kirche", "Kirche:",
                                     c("selten" = "kirche_selten",
                                       "manchmal" = "kirche_manchmal",
                                       "oft" = "kirche_oft"))
                 )
               )),
      tabPanel("Position",
               plotOutput("mca_studienalltag_sup_ind", width = "1200px", height = "750px")
      )#,
      # tabPanel("Position Tabelle",
      #          textOutput("mca_studienalltag_sup_ind_tab")
      # )
    )
  )
))
