
# This is the user-interface definition of a Shiny web application.
# You can find out more about building applications with Shiny here:
#
# http://shiny.rstudio.com
#

library(shiny)

shinyUI(fluidPage(

  # Application title
  titlePanel("Locate! — Den eigenen Alltag im Wintersemester 2015/2016 vergleichen."),

    mainPanel(
      tabsetPanel(
        tabPanel("Dateneingabe",
                 fluidRow(
                   column(4,
                   h4("Persönliche Situation"),
                   textInput("name", "Name:", "Jean-Paul"),
                   radioButtons("wohnort", "Wohnort während dem Semester:",
                                c("Wohnort: eigene Wohnung",
                                  "Wohnort: Eltern",
                                  "Wohnort: Partner/in",
                                  "Wohnort: WG/ Wohnheim")),
                   radioButtons("entfernung_ph", "Entfernung des Wohnorts zur PH:",
                                c("0 bis 20km", 
                                  "20 bis 50km", 
                                  "50 bis 150km")),
                   radioButtons("finanzierung_eltern", "Finanzierung durch die Eltern:",
                                c("hauptsächlich" = "finanzierung_eltern_hauptsächlich",
                                  "nein" = "finanzierung_eltern_nein",
                                  "teilweise" = "finanzierung_eltern_teilweise")),
                   radioButtons("finanzierung_bafoeg", "Finanzierung durch BAföG:",
                                c("hauptsächlich" = "finanzierung_bafög_hauptsächlich",
                                  "nein" = "finanzierung_bafög_nein",
                                  "teilweise" = "finanzierung_bafög_teilweise")),
                   radioButtons("finanzierung_arbeit_vorlesungszeit", "Finanzierung durch Arbeit während dem Semester:",
                                c("hauptsächlich" = "finanzierung_arbeit_vorlesungszeit_hauptsächlich",
                                  "nein" = "finanzierung_arbeit_vorlesungszeit_nein",
                                  "teilweise" = "finanzierung_arbeit_vorlesungszeit_teilweise")),
                   radioButtons("finanzierung_arbeit_semesterferien", "Finanzierung durch Arbeit während den Semesterferien:",
                                c("hauptsächlich" = "finanzierung_arbeit_semesterferien_hauptsächlich",
                                  "nein" = "finanzierung_arbeit_semesterferien_nein",
                                  "teiweise" = "finanzierung_arbeit_semesterferien_teilweise")),
                   radioButtons("finanzielle_situation", "Finanzielle Situation:",
                                c("gut",              
                                  "schlecht",
                                  "weder gut noch schlecht"))
                   ),
                   column(4,
                          h4("Gewöhnliche Studienwoche"),
                          radioButtons("zeitmuster", "Geschätztes Zeitmuster:",
                                      c("Zeitmuster 1: Freizeit",
                                        "Zeitmuster 2: Selbststudium",
                                        "Zeitmuster 3: Erwerbsarbeit",
                                        "Zeitmuster 4: Pendler/innen")),
                          radioButtons("lehrveranstaltungen_anzahl", "Anzahl der besuchten Lehrveranstaltungen:",
                                      c("11 bis 12 Veranstaltungen", 
                                        "13 Veranstaltungen",    
                                        "bis 10 Veranstaltungen",
                                        "mehr als 13 Veranstaltungen")),
                          radioButtons("lernort_alleine", "Lieblingslernort alleine:",
                                      c("Lernort: PH",
                                        "Lernort: PH und Zuhause",
                                        "Lernort: Zuhause")),
                          radioButtons("selbstorganisierte_lerngruppe", "Teilnahme an einer Lerngruppe:",
                                      c("Lerngruppe: gelegentlich",
                                        "Lerngruppe: ja",        
                                        "Lerngruppe: nein")),
                          radioButtons("aufmerksamkeit", "Zeit mit der größten Aufmerksamkeit:",
                                      c("Aufmerksamkeit: abends",
                                        "Aufmerksamkeit: mittags",            
                                        "Aufmerksamkeit: morgens",         
                                        "Aufmerksamkeit: nachmittags")),
                          radioButtons("sitzplatz", "Lieblingsposition in einem Seminarzimmer:",
                                      c("Sitzplatz: hinteres Drittel",
                                        "Sitzplatz: Mitte",
                                        "Sitzplatz: vorderes Drittel")),
                          radioButtons("sitzplatz_identisch", "Identischer Sitzplatz",
                                      c("Sitzplatz identisch: ab und zu",
                                        "Sitzplatz identisch: immer",
                                        "Sitzplatz identisch: oft",
                                        "Sitzplatz identisch: selten"))
                   ),
                   column(4,
                          h4("Studienalltag an der PH"),
                          radioButtons("ph_hsb_recherchieren", "In der HSB recherchieren:",
                                      c("nie" = "ph_hsb_recherchieren_nie",
                                        "oft" = "ph_hsb_recherchieren_oft",
                                        "selten" = "ph_hsb_recherchieren_selten",
                                        "manchmal" = "ph_hsb_recherchieren_manchmal")),
                          radioButtons("ph_hsb_lernen", "In der HSB lernen:",
                                      c("nie" = "ph_hsb_lernen_nie",
                                        "oft" = "ph_hsb_lernen_oft",
                                        "selten" = "ph_hsb_lernen_selten",
                                        "manchmal" = "ph_hsb_lernen_manchmal")),
                          radioButtons("mensa_essen", "In der Mensa essen:",
                                      c("nie" = "mensa_essen_nie",
                                        "oft" = "mensa_essen_oft",
                                        "selten" = "mensa_essen_selten",
                                        "manchmal" = "mensa_essen_manchmal")),
                          radioButtons("cafete_essen", "In der Cafete essen:",
                                      c("nie" = "cafete_essen_nie",
                                        "oft" = "cafete_essen_oft",
                                        "selten" = "cafete_essen_selten",
                                        "manchmal" = "cafete_essen_manchmal")),
                          radioButtons("computerräume_nutzen", "Computerräume nutzen:",
                                      c("nie" = "computerräume_nutzen_nie",
                                        "oft" = "computerräume_nutzen_oft",
                                        "selten" = "computerräume_nutzen_selten",
                                        "manchmal" = "computerräume_nutzen_manchmal")),
                          radioButtons("campus_lernen", "Am Campus lernen:",
                                      c("nie" = "campus_lernen_nie",
                                        "oft" = "campus_lernen_oft",
                                        "selten" = "campus_lernen_selten",
                                        "manchmal" = "campus_lernen_manchmal")),
                          radioButtons("campus_entspannen", "Am Campus entspannen:",
                                      c("nie" = "campus_entspannen_nie",
                                        "oft" = "campus_entspannen_oft",
                                        "selten" = "campus_entspannen_selten",
                                        "manchmal" = "campus_entspannen_manchmal")),
                          radioButtons("austausch_lehrende", "Mit Lehrenden austauschen:",
                                      c("nie" = "austausch_lehrende_nie",
                                        "oft" = "austausch_lehrende_oft",
                                        "selten" = "austausch_lehrende_selten",
                                        "manchmal" = "austausch_lehrende_manchmal")),
                          radioButtons("ph_kommilitoninnen_entspannen", "Mit Kommiliton/innen entspannen:",
                                      c("nie" = "ph_kommilitoninnen_entspannen_nie",
                                        "oft" = "ph_kommilitoninnen_entspannen_oft",
                                        "selten" = "ph_kommilitoninnen_entspannen_selten",
                                        "manchmal" = "ph_kommilitoninnen_entspannen_manchmal")),
                          radioButtons("ph_kommilitoninnen_lernen", "Mit Kommiliton/innen lernen:",
                                      c("nie" = "ph_kommilitoninnen_lernen_nie",
                                        "oft" = "ph_kommilitoninnen_lernen_oft",
                                        "selten" = "ph_kommilitoninnen_lernen_selten",
                                        "manchmal" = "ph_kommilitoninnen_lernen_manchmal"))
                   ),
                   column(4,
                          h4("Studienalltag außerhalb der PH"),
                          radioButtons("ka_essen", "In Karlsruhe essen:",
                                      c("nie" = "ka_essen_nie",
                                        "oft" = "ka_essen_oft",
                                        "selten" = "ka_essen_selten",
                                        "manchmal" = "ka_essen_manchmal")),
                          radioButtons("ka_entspannen", "In Karlsruhe entspannen:",
                                      c("nie" = "ka_entspannen_nie",
                                        "oft" = "ka_entspannen_oft",
                                        "selten" = "ka_entspannen_selten",
                                        "manchmal" = "ka_entspannen_manchmal")),
                          radioButtons("bahn_lernen", "In der Bahn lernen:",
                                      c("nie" = "bahn_lernen_nie",
                                        "oft" = "bahn_lernen_oft",
                                        "selten" = "bahn_lernen_selten",
                                        "manchmal" = "bahn_lernen_manchmal")),
                          radioButtons("fremder_wohnort_lernen", "An einem fremden Wohnort lernen:",
                                      c("nie" = "fremder_wohnort_lernen_nie",
                                        "oft" = "fremder_wohnort_lernen_oft",
                                        "selten" = "fremder_wohnort_lernen_selten",
                                        "manchmal" = "fremder_wohnort_lernen_manchmal")),
                          radioButtons("kommilitoninnen_treffen", "Mit Kommiliton/innen treffen:",
                                      c("nie" = "kommilitoninnen_treffen_nie",
                                        "oft" = "kommilitoninnen_treffen_oft",
                                        "selten" = "kommilitoninnen_treffen_selten",
                                        "manchmal" = "kommilitoninnen_treffen_manchmal")),
                          radioButtons("kommilitoninnen_lernen", "Mit Kommiliton/innen lernen:",
                                      c("nie" = "kommilitoninnen_lernen_nie",
                                        "oft" = "kommilitoninnen_lernen_oft",
                                        "selten" = "kommilitoninnen_lernen_selten",
                                        "manchmal" = "kommilitoninnen_lernen_manchmal"))
                   ),
                   column(4,
                          h4("Gewöhnliche Internetnutzung für das Studium"),
                          radioButtons("website_nutzen", "PH Website nutzen:",
                                      c("oft" = "website_nutzen_oft",
                                        "selten" = "website_nutzen_selten",
                                        "manchmal" = "website_nutzen_manchmal")),
                          radioButtons("web_services_andere_nutzen", "Andere Web Services nutzen:",
                                      c("nie" = "web_services_andere_nutzen_nie",
                                        "oft" = "web_services_andere_nutzen_oft",
                                        "selten" = "web_services_andere_nutzen_selten",
                                        "manchmal" = "web_services_andere_nutzen_manchmal")),
                          radioButtons("emails_lehrende", "E-Mails an Lehrende schreiben:",
                                      c("nie" = "emails_lehrende_nie",
                                        "oft" = "emails_lehrende_oft",
                                        "selten" = "emails_lehrende_selten",
                                        "manchmal" = "emails_lehrende_manchmal")),
                          radioButtons("emails_kommilitoninnen", "E-Mails an Kommiliton/innen schreiben:",
                                      c("nie" = "emails_kommilitoninnen_nie",
                                        "oft" = "emails_kommilitoninnen_oft",
                                        "selten" = "emails_kommilitoninnen_selten",
                                        "manchmal" = "emails_kommilitoninnen_manchmal")),
                          radioButtons("internetrecherche", "Im Internet recherchieren:",
                                      c("manchmal" = "internetrecherche_manchmal",
                                        "oft" = "internetrecherche_oft",
                                        "selten" = "internetrecherche_selten")),
                          radioButtons("soziale_netzwerke_studieren", "Soziale Netzwerke fürs Studium nutzen:",
                                      c("nie" = "soziale_netzwerke_studieren_nie",
                                        "oft" = "soziale_netzwerke_studieren_oft",
                                        "selten" = "soziale_netzwerke_studieren_selten"
                                        ))
                   ),
                   column(4,
                          h4("Alltägliche Freizeitaktivitäten"),
                          radioButtons("fernsehen", "Fernsehen:", 
                                      c("manchmal" = "fernsehen_manchmal",
                                        "oft" = "fernsehen_oft",   
                                        "selten" = "fernsehen_selten")),
                          radioButtons("musik", "Musik:",
                                      c("manchmal" = "musik_manchmal",
                                        "oft" = "musik_oft",   
                                        "selten" = "musik_selten")),
                          radioButtons("kino", "Kino:",
                                      c("manchmal" = "kino_manchmal",
                                        "oft" = "kino_oft",   
                                        "selten" = "kino_selten")),
                          radioButtons("freunde_treffen", "Freunde treffen:",
                                      c("manchmal" = "freunde_treffen_manchmal",
                                        "oft" = "freunde_treffen_oft",   
                                        "selten" = "freunde_treffen_selten")),
                          radioButtons("soziale_netzwerke", "Soziale Netzwerke nutzen:",
                                      c("manchmal" = "soziale_netzwerke_manchmal",
                                        "oft" = "soziale_netzwerke_oft",   
                                        "selten" = "sozile_netzwerke_selten")),
                          radioButtons("internet_surfen", "Im Internet surfen:",
                                      c("manchmal" = "internet_surfen_manchmal",
                                        "oft" = "internet_surfen_oft",   
                                        "selten" = "internet_surfen_selten")),
                          radioButtons("chillen", "Chillen:",
                                      c("manchmal" = "chillen_manchmal",
                                        "oft" = "chillen_oft",   
                                        "selten" = "chillen_selten")),
                          radioButtons("bücher", "Bücher lesen:",
                                      c("manchmal" = "bücher_manchmal",
                                        "oft" = "bücher_oft",   
                                        "selten" = "bücher_selten")),
                          radioButtons("zeitungen", "Zeitungen lesen:",
                                      c("manchmal" = "zeitungen_manchmal",
                                        "oft" = "zeitungen_oft",   
                                        "selten" = "zeitungen_selten")),
                          radioButtons("disco", "In die Disco gehen:",
                                      c("manchmal" = "disco_manchmal",
                                        "oft" = "disco_oft",   
                                        "selten" = "disco_selten")),
                          radioButtons("sport", "Sport:",
                                      c("manchmal" = "sport_manchmal",
                                        "oft" = "sport_oft",   
                                        "selten" = "sport_selten")),
                          radioButtons("familie", "Etwas mit der Familie unternehmen:",
                                      c("manchmal" = "familie_manchmal",
                                        "oft" = "familie_oft",   
                                        "selten" = "familie_selten")),
                          radioButtons("shoppen", "Shoppen:",
                                      c("manchmal" = "shoppen_manchmal",
                                        "oft" = "shoppen_oft",   
                                        "selten" = "shoppen_selten")),
                          radioButtons("kreatives", "Kreatives tun:",
                                      c("manchmal" = "kreatives_manchmal",
                                        "oft" = "kreatives_oft",   
                                        "selten" = "kreatives_selten")),
                          radioButtons("kirche", "Kirche:",
                                      c("manchmal" = "kirche_manchmal",
                                        "oft" = "kirche_oft",   
                                        "selten" = "kirche_selten")),
                          radioButtons("ehrenamt", "Ehrenamtliches Engagement:",
                                      c("manchmal" = "ehrenamt_manchmal",
                                        "oft" = "ehrenamt_oft",   
                                        "selten" = "ehrenamt_selten"))
                   )
                )),
        tabPanel("Position",
                 plotOutput("mfa_studienalltag_sup_ind", width = "100%")
                 ),
        tabPanel("Antwortmuster horizontal",
                 plotOutput("mfa_studienalltag_achse_1", width = "100%")
                 ),
        tabPanel("Antwortmuster vertikal",
                 plotOutput("mfa_studienalltag_achse_2", width = "100%")
                 )
      )
    )
))
